services:
  db:
    image: postgres:15-alpine
    container_name: christina-db
    restart: always
    profiles: ["dev", "prod"]
    environment:
      POSTGRES_USER: ${DB_USER:-myuser}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-mypassword}
      POSTGRES_DB: ${DB_NAME:-christina_db}
    volumes:
      - postgres_data_prod:/var/lib/postgresql/data
    networks:
      - app_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis_cache:
    image: redis:7-alpine
    container_name: christina-redis
    restart: always
    profiles: ["dev", "prod"]
    volumes:
      - redis_data:/data
    networks:
      - app_network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  server:
    platform: linux/amd64
    build:
      context: .
      dockerfile: Dockerfile
    image: softvence/christina-server:latest
    container_name: christina-server
    restart: always
    profiles: ["dev", "prod"]
    ports:
      - "9099:9099"
    env_file:
      - .env
    environment:
      DATABASE_URL: postgresql://${DB_USER:-myuser}:${DB_PASSWORD:-mypassword}@db:5432/${DB_NAME:-christina_db}
      REDIS_HOST: redis_cache
      REDIS_PORT: 6379
      REDIS_CONNECTION_URL: redis://redis_cache:6379
    # volumes:
    #   - ./uploads:/usr/src/app/uploads
    depends_on:
      db:
        condition: service_healthy
      redis_cache:
        condition: service_healthy
    networks:
      - app_network

networks:
  app_network:
    driver: bridge

volumes:
  postgres_data_prod:
  redis_data: