

version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: christina_DB
    restart: always
    ports:
      - "5438:5432" 
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: christinaDB
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data
    networks:
      - app_network
  redis_cache:
    image: redis:7-alpine
    container_name: christina_redis_server
    restart: always
    ports:
      - "6379:6379" 
    volumes:
      - redis_data_dev:/data 
    networks:
      - app_network
 
networks:
  app_network:
    driver: bridge

volumes:
  postgres_data_dev:
  redis_data_dev:
